### ISSUE TITLE
[BUG] Unable to sort non-Watchlist playlists

### ISSUE THREAD

**Issue by richardmtl** [KohGeek/SortYoutubePlaylistByDuration#7] opened 2024-08-07 12:45 UTC
**Describe the bug**
Now that #5 is fixed, I figured I'd bring up this other issue that I started having. As mentioned in that issue, I have to refresh the page in order to show the UI. If I do this on a playlist other than the Watchlist, and then hit the "Sort videos" button, it doesn't sort them. The thing is, sometimes it'll work fine for a week or more, and then it'll stop working. I suspect that things change depending the version of Chrome Canary I'm on

**To Reproduce**
1. Go to a private playist
2. Make sure it's set to "Shortest First" and "Sort all" 
3. Hit "Sort Videos"

**Expected behavior**
It will Sort the playlist by length

**Actual Behaviour**
It gets stuck: "Loading more videos - 185 videos loaded"  (I have tried with playlists of only 25 videos, so it's not a matter of the number of videos).

**Platform (please complete the following information):**
 - Browser: Chrome Canary
 - Version: Version 129.0.6642.0 (Official Build) canary (arm64) - MacOS
 - Scriptrunner: TamperMonkey
 - Scriptrunner version: 5.1.1

**Additional context**
Like I mentioned, sometimes it will work as expected for a few days or a few weeks, and then one day, it just stops working and exhibits the same "stuck" behaviour.

**Comment by KohGeek** [comment] 2024-08-07 15:29
I may have identified the root cause of this issue. The current script grabs the number of thumbnails, not draggable points. So it counts recommendations and stuff too. I'll see if fixing this will work

**Comment by KohGeek** [comment] 2024-08-08 04:15
Should be fixed. Spinner detection is inconsistent so I went through grabbing the reported video count instead.

**Closed** 2024-08-08 04:20 UTC
