### ISSUE TITLE
[BUG] Stopped working in Canary

### ISSUE THREAD

**Issue by richardmtl** [KohGeek/SortYoutubePlaylistByDuration#3] opened 2024-03-19 14:41 UTC
**Describe the bug**

This script worked fine in Chrome Canary up until yesterday, but today it no longer shows the buttons when I go to https://www.youtube.com/playlist?list=WL and Refresh as usual (the Refresh was always required to show the buttons, in my experience).

It still works in Chrome Version 122.0.6261.129 (Official Build) (arm64) with Tampermonkey 5.0.1

**To Reproduce**

1. Install Canary (Version 124.0.6367.0 (Official Build) canary (arm64)
2. Go to https://www.youtube.com/playlist?list=WL
3. Reload the page
4. No buttons appear

**Platform (please complete the following information):**
 - Scriptrunner: Tampermonkey 5.1.0  (note the version difference from Chrome; 5.0.1 vs 5.1.0)
 - Script version 3.0.1
 
Yes, I have Developer Mode enabled in Canary.

**Comment by KohGeek** [comment] 2024-03-19 19:59
Hi, can I get a confirmation on the device you're running this on? It seems you're running arm64 version of Chrome and I'm not sure if AMD64 chrome can fully replicate this.

Will try still on my side.

**Comment by richardmtl** [comment] 2024-03-19 20:04
Yup! Macbook Air M2 (2023).

**Comment by KohGeek** [comment] 2024-03-19 20:15
Noted, thanks! I'll try to get it pinned down if I ever get canary running on my system, so far it just shows a white screen haha

**Comment by richardmtl** [comment] 2024-03-19 20:19
Thanks for checking! I figured it was important to note because if it's something specific to Canary, then eventually it'll hit production Chrome and others will run into the same problem. But maybe the Canary bit is a red herring and it's the Tampermonkey version? Good luck, let me know if I can try something to help!

(btw I use this to sort a WL that is, um, nearly 5k. That's the reason I run it in Canary. I launch canary, refresh the WL page, make it sort (it handles 1-3 at a time), and then I quit Canary because otherwise it'll just die on its own anyway). I wish Google just added that function on their end!!

**Comment by KohGeek** [comment] 2024-03-19 20:27
When you right click on Tampermonkey, can you show me what you see? This is what I am seeing so far:

<img width="232" alt="image" src="https://github.com/KohGeek/SortYoutubePlaylistByDuration/assets/6839340/2bbcbf9f-e3cd-40a6-ae15-6e82fbbedfd7">

Basically, Tampermonkey does not recognise the link for some reason. Need to make sure it's the same on your end too.

**Comment by richardmtl** [comment] 2024-03-19 20:34
Same here, "No script is running"..  But I did enable developer mode, I saw the notice about that.

**Comment by KohGeek** [comment] 2024-03-19 20:39
That's very unfortunate, I'd like you to help me check whether everything is in place, can you post some screenshots here like the ones below?

### Extensions:
<img width="1440" alt="image" src="https://github.com/KohGeek/SortYoutubePlaylistByDuration/assets/6839340/bbe56a72-810a-4587-8975-6dd18f52a5e4">

### Tampermonkey Script Settings:
<img width="1440" alt="image" src="https://github.com/KohGeek/SortYoutubePlaylistByDuration/assets/6839340/72bb156e-b93a-4a03-ac45-4e15fcde86ba">

**Comment by richardmtl** [comment] 2024-03-19 20:49
<img width="1291" alt="Screenshot 2024-03-19 at 4 46 35 PM" src="https://github.com/KohGeek/SortYoutubePlaylistByDuration/assets/3676359/201f935a-0201-4328-83ff-446b98e08188">
<img width="1677" alt="Screenshot 2024-03-19 at 4 48 25 PM" src="https://github.com/KohGeek/SortYoutubePlaylistByDuration/assets/3676359/67861f09-125f-403d-b058-05a52f355c3a">

Ignore the "position" setting; the script in position 1 is your 2.0.6 version, currently disabled (I only realized you had a new version today when I found this repo).

**Comment by KohGeek** [comment] 2024-03-19 20:55
Yeah it's fine haha, I migrated a while ago. I don't think it affects the outcome either though I suppose I should try?

Are you sure the final address of the Watch Later list is https://www.youtube.com/playlist?list=WL ?

**Comment by richardmtl** [comment] 2024-03-19 21:02
Indeed it is https://www.youtube.com/playlist?list=WL , I checked that too (I work in tech too so I checked everything I could think of before opening this issue, ha!).

Quite the mystery! Yesterday it was fine and today it is not.

**Comment by KohGeek** [comment] 2024-03-19 21:06
Haha, sorry about that, just double checking everything. 

So I ran through the scenario that you have here and I simply cannot replicate it. I'm not entirely sure whether this is because of arm64 chrome being different, or Tampermonkey not working Chrome on ARM. It works completely fine on my end.

`Canary Version 124.0.6367.0 amd64, Windows 11 22621.2715`

**Comment by richardmtl** [comment] 2024-03-19 21:12
HA, glad you found it! Hope you can find a fix for it, and I appreciate your attention!

**Comment by KohGeek** [comment] 2024-03-19 21:25
Last thing to clarify for you, sorry for the back and forth. Is this the only script with this problem so far? As in, not detecting the webpage

**Comment by richardmtl** [comment] 2024-03-19 21:35
It's the only script I use, so I couldn't tell you. If you had an easy-to-test script that I can pop into Tampermonkey, I'd be happy to try!

**Comment by KohGeek** [comment] 2024-03-19 21:40
https://greasyfork.org/en/scripts/457205-unhold-youtube-resource-locks

Here's one, my testing so far seems to indicate that all userscript just stops working

**Comment by richardmtl** [comment] 2024-03-19 21:51
I can't test right now but your conclusion seems likely! I'll test and report tomorrow. Thanks very much for your help!

**Comment by KohGeek** [comment] 2024-03-19 21:54
Thanks for the reporting. I can confirm it's Tampermonkey now. 

- Go to TamperMonkey settings
- Set config mode to Advanced. 
- Scroll down to Experimental - Inject Mode, switch it to `Instant`

The script should now work again. 

Closing this issue and linking to the TamperMonkey issue later.

**Closed by KohGeek** 2024-03-19 21:54 UTC
Labels: bug, help wanted, med priority, chromium, cannot replicate

**Comment by richardmtl** [comment] 2024-03-20 12:33
Thanks for opening the bug report there, you did a much more complete job than I would have been able to do!

**Comment by richardmtl** [comment] 2024-03-20 12:35
Oh and for me, switching to `Insert` did not fix it, but their work-around did:

**Temporary resolution**
Goto [Chrome Experiments](chrome://flags/), find & enable Enable (deprecated) synchronous mutation events , restart chrome, all user scripts come back again.
